Refactor and UI improvement
ical10/perma-tweeter pull request #6
Opened 2022-12-21 15:53 UTC by ical10

Implemented feedbacks on:

1. Use polkadot lib for Identicon instead of hard-coding base64 to string
2. Move getAuthor and only use once
3. Return without `temp` var
4. Use `clsx` for complex logic in className
5. Use `const` for `BASE_TWITTER_URL`
6. Remove code related to `mnemonic`
7. Remove `title`, `tags`, change `canonical` to `tweet`, and convert `body` into MD with links for usernames and hashtags
8. Refactor `createPostWithSpaceId`, `createSpaceWithTweet`, and `postTransaction`
9. Use `const` for `polkaverseContentURL`
10. Refactor converting only once for `Boolean()`
11. Create `config` file in `src/configs`

Note: removed `IS_ABOVE_LIMIT` because it is not used.

2022-12-22 10:03 UTC, olehmell requested changes

2022-12-22 10:03 UTC, olehmell commented on src/components/TwitterUserProfileCard.tsx
> +            "text-[#A0ADB4]": disabled,
You use #A0ADB4 in few places, so should be as a var

2022-12-22 10:03 UTC, olehmell commented on src/components/render/TweetBody.tsx
> +        a: ({ node, ...props }) => <a className="text-[#316CF4]" {...props} />,
#316CF4 same story

2022-12-22 10:03 UTC, olehmell commented on src/utils/string.ts
> +  const markdownReady = hashtagParsed.replace(/@(\w+)/g, "[@$1](https://twitter.com/$1)");
Please extract as separate functions or add a comment that the first regex is for a hashtag and the second for usernames. 

Because I had to read regex to understand what is it

2022-12-22 12:47 UTC, ical10 commented on src/components/ReactIdenticon.tsx
> +    address = "5DSg6JpKCjKVSEEKzVtoSkszpMu3NUfWEs7WiDcCxzhXksCV",
I was trying to set Identicon placeholder for spaces (sometimes a space doesn't have an avatar/image). But I changed it into using grey avatar. Will remove this code.

2022-12-23 12:44 UTC, olehmell approved these changes

2022-12-23 12:52 UTC, merged