Fix/implement feedbacks
ical10/perma-tweeter pull request #7
Opened 2022-12-26 16:03 UTC by ical10

Note: Please merge #8 first before merging this one (easier for rebasing).

2022-12-28 11:29 UTC, olehmell requested changes

2022-12-28 11:29 UTC, olehmell commented on src/hooks/use-subsocial-api.ts
>          minWidth: "300px",
Maybe add wrapper like `TxToast` that will be include `minWidth`, because now we have the width in few places

2022-12-29 10:39 UTC, ical10 commented on src/hooks/use-subsocial-api.ts
>          minWidth: "300px",
Applied in 0ef8050

2022-12-29 16:57 UTC, olehmell approved these changes

2022-12-29 17:06 UTC, merged