Unit test/markdown parser
ical10/perma-tweeter pull request #8
Opened 2022-12-26 16:04 UTC by ical10

2022-12-28 11:37 UTC, olehmell requested changes

2022-12-28 11:37 UTC, olehmell commented on __tests__/markdown-parser.test.ts
> +const inputUsernameWithCharPrefix = "123@TwitterSupport";
Lets collect all constants to object with name like `mocks`

2022-12-28 11:37 UTC, olehmell commented on __tests__/markdown-parser.test.ts
> +    expect(textToMarkdownParser(longTweet)).toBeDefined();
You have functions `parseHashtags` and `parseUsername`, but here you have `textToMarkdownParser`. Why do you not follow one style for all, like `parseTextToMarkdown`

2022-12-29 10:15 UTC, ical10 commented on __tests__/markdown-parser.test.ts
> +    expect(textToMarkdownParser(longTweet)).toBeDefined();
Applied in 5557504

2022-12-29 10:15 UTC, ical10 commented on __tests__/markdown-parser.test.ts
> +const inputUsernameWithCharPrefix = "123@TwitterSupport";
Applied in 5557504

2022-12-29 17:03 UTC, olehmell approved these changes

2022-12-29 17:05 UTC, merged